# Use OpenJDK as the base image
FROM eclipse-temurin:17-jdk-jammy

# Set the working directory in the container
WORKDIR /app

# Copy the packaged Spring Boot application JAR file into the container
COPY target/BackEnd-Password-Manager-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the port that your Spring Boot application uses (if any)
EXPOSE 8080

# Define a command to run the Spring Boot application when the container starts
CMD ["java", "-jar", "app.jar"]
